## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## position controller
joint_posvel_controller:
  type: posvel_controllers/JointPosVelController
  joint: wsg50_finger_left_joint

    
wsg50_grasping_controller:
  type: wsg50_grasping_controller/WSG50GraspingController